### ISSUE TITLE
[BUG] New business profiles are not loading correctly

### ISSUE THREAD

**Issue by ThugDebugger** [Rebuild-Black-Business/RBB-Website#373] opened 2020-11-08 15:20 UTC
**IMPORTANT NOTE**

This issue is superseded by #374 -- Do not work on this issue for the time being. We will likely close it once #374 is completed. It is also a duplicate of #371 .

**Describe the bug**
Sometimes when a new business is added, the profile page doesn't generate correctly which then results in a 404

**To Reproduce**
1. Go to 'https://www.rebuildblackbusiness.com/business/legendaire-distilled-spirits-recuRbLuz6ZWIZI95'
2. See error

**Expected behavior**
The standard profile page should pull up for the business "Legendaire Distilled Spirits"

**Actual Behavior**
404 is happening, which results in the 404-page being shown

**Bonus**
Correct the 404-page width and height from overflowing, and instead should fit within the screen's container

**Comment by elchris** [comment] 2020-11-09 04:09
as discussed in discord, this issue is a duplicate of #371 but it's also very helpful in describing the problem.

**Comment by elchris** [comment] 2020-11-13 21:03
This was fixed by #374 - thank you @Mhmdabed11 

Note, the new url for the above business is:

- https://www.rebuildblackbusiness.com/business/legendaire-distilled-spirits-13695

**Comment by elchris** [comment] 2020-11-13 21:04
see above comment

**Closed** 2020-11-13 21:04 UTC
Labels: bug
